### PR TITLE
TEST initial checkin for long weekend testing

### PR DESCRIPTION
**Pull request by workingmonk**

### CODE REVIEW

**Comment by tpmanley** [comment]
Looks good. I assume that you have run all these for a few minutes and they are working as expected? Have you removed power from the devices an confirmed that you get the failure data that you expect?

**Comment by workingmonk** [comment]
except for the removing part. doing that now. the checkin percentage should go down

**Comment by workingmonk** [comment]
screen shot 2016-09-02 at 6 24 26 pm

**Comment by workingmonk** [comment]
after removing the device for a while:

screen shot 2016-09-02 at 6 25 02 pm

**Comment by tpmanley** [comment]
Looking good :+1:

**Pull request closed without merging**
